on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

name: Mobile Build
jobs:
  build:
    name: Build and test APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '15'
    - uses: subosito/flutter-action@v1
      with:
        # channel: 'stable'
        flutter-version: '2.0.3'
    - name: Get Flutter packages
      run: |
        cd mobile
        flutter pub get
    - name: Run Flutter tests
      run: |
        cd mobile
        flutter test
    - name: Build APK
      run: |
        cd mobile
        flutter build apk --debug
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: APKs
        path: mobile/build/app/outputs/apk/debug/app-*.apk

